# Configuration for weekly-digest - https://github.com/apps/weekly-digest
    publishDay: 2
    canPublishIssues: true
    canPublishPullRequests: true
    canPublishContributors: true
    canPublishStargazers: true
    canPublishCommits: true
  
